version: "3.8"

services:
  fit_galgo_api:
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    ports:
      - "8000:80"
    networks:
      - fit_galgo_network
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    env_file:
      - ./app/.env
    depends_on:
      - fit_galgo_mongodb

  fit_galgo_mongodb:
    image: mongo:latest
    ports:
      - "27117:27017"
    networks:
      - fit_galgo_network
    volumes:
      - mongodb_data:/data/db

  fit_galgo_mongodb_test:
    image: mongo:latest
    ports:
      - "27217:27017"
    networks:
      - fit_galgo_network
    volumes:
      - mongodb_test_data:/data/db

networks:
  fit_galgo_network:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_test_data:
