version: "3.8"

services:
  fit_galgo_api:
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    ports:
      - "8000:80"
    networks:
      - fit_galgo_network
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests

  fit_galgo_couchbase_node1:
    image: couchbase:7.2.2
    volumes:
      - "./couchbase/node1:/opt/couchbase/var"
  fit_galgo_couchbase_node2:
    image: couchbase:7.2.2
    volumes:
      - "./couchbase/node2:/opt/couchbase/var"
  fit_galgo_couchbase_node3:
    image: couchbase:7.2.2
    volumes:
      - "./couchbase/node3:/opt/couchbase/var"
    ports:
      - "8091:8191"

networks:
  fit_galgo_network:
    driver: bridge

volumes:
  couchbase: